[package]
name = "tts-bot-core"
version = "0.0.0"
edition = "2024"

[dependencies]
anyhow = "1"
async-trait = "0.1"
base64 = "0.23"
derivative = "2"
futures = "0.3"
hex = "0.4"
hound = "3"
indexmap = { version = "2", features = ["serde"] }
json = "0.12"
regex = "1"
reqwest = { version = "0.13", features = ["rustls", "json", "http2"], default-features = false }
rubato = "5"
serde = { version = "1", features = ["derive"] }
sha2 = "0.11"
ssml = "0.2"
structstruck = "0.5"
symphonia = { version = "0.6", features = ["mp3", "pcm"], default-features = false }
tap = "1"
tokio = { version = "1", features = ["sync"] }
tokio-tungstenite = "0.30"
toml = { version = "1", features = ["preserve_order"] }
tracing = "0.1"
tungstenite = "0.30"
url = { version = "2", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
